import { chromium } from 'playwright-core';
import fs from 'fs';
const exe = fs.readdirSync('/opt/pw-browsers').filter(d => d.startsWith('chromium-'))[0];
const browser = await chromium.launch({ executablePath: `/opt/pw-browsers/${exe}/chrome-linux/chrome`, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--use-gl=angle'] });
const p = await (await browser.newContext({ viewport: { width: 1440, height: 860 }, deviceScaleFactor: 1 })).newPage();
await p.goto('http://127.0.0.1:5173/');
await p.waitForFunction(() => !document.querySelector('#stage.busy') && window.__bf?.model);
await p.waitForTimeout(1500); await p.screenshot({ path: 'shots/30-final-home.png' });
console.log(await p.title(), await p.locator('.logo').innerText(), await p.locator('#themes').count());
await browser.close();
